name: 'Continuous Delivery'

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: fastapi-service
  REGION: us-central1
  LOG_LEVEL: DEBUG
  THRESHOLD_IN_MINUTES: 15
  BUCKET_NAME: model-challenge
  MODEL_FILE: model_file/delay_model.json
  DATASET_FILE: datasets/data.csv

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    - name: Build and Push Docker Image
      run: |
        gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated \
          --set-env-vars LOG_LEVEL=${{ env.LOG_LEVEL }},THRESHOLD_IN_MINUTES=${{ env.THRESHOLD_IN_MINUTES }},BUCKET_NAME=${{ env.BUCKET_NAME }},MODEL_FILE=${{ env.MODEL_FILE }},DATASET_FILE=${{ env.DATASET_FILE }} \
          --http-health-check-path /health \
          --timeout 1 \
          --http-health-check-interval 30 \
          --http-health-check-timeout 1 \
          --http-health-check-failure-threshold 3